name: Theme deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Get latest tag
        id: get_latest_tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate theme name
        id: generate_theme_name
        run: |
          echo "THEME_NAME=theme-${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Install dependencies
        run: |
          npm install --no-optional=false
          npm install @parcel/watcher-linux-x64-glibc@2.2.0 --no-save
          npm install @tailwindcss/oxide-linux-x64-gnu --no-save

      - name: Build Tailwind CSS
        run: npm run tailwind:build

      - name: Upload theme
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_CLI_TTY: 0
        run: |
          shopify theme push -p --theme="${{ env.THEME_NAME }}" 
